### ISSUE TITLE
De filter op Startdatum op het Opstellen scherm werkt niet goed

### ISSUE THREAD

**Issue by RitaBerghuis** [maykinmedia/archiefbeheercomponent#215]
Als ik voor het eerst het scherm open,  staan er twee zaken met startdatum 3-8-2020 en archiefactiedatum 3-8-2021.
Als ik vervolgens startdatum aanpas naar vandaag (9-4-2021) dan verdwijnen de zaken niet meteen, maar pas als ik op een ander selectievakje op het scherm druk (geprobeerd met chrome en edge).
Vervolgens kan ik de selectie op startdatum niet meer verwijderen, dit lukt mij alleen door van het scherm af te gaan en weer opnieuw te starten met het opstellen van een lijst.

Voordat dit opgelost wordt, lijkt het me handig om te discussiëren of het filter op startdatum van de zaak een nuttig filter is. Zie ook #89 Gaat het om filtering op startdatum van de zaak, of op archiefactiedatum? Voorstel voor nu is, om het filter op startdatum van het scherm te halen. 

**N.B**: dit zijn bevindingen in de demoversie
In de omschrijving bij de demo versie staat als omschrijving bij het filter "of door de minimale datum waarop vernietigd mag worden mee te geven." => dat zou volgens mij niet gefilterd moeten worden op de startdatum van de zaak.

**Comment by joeribekker** [comment]
@silvia Staat het zaak startdatum filter er nog in? Zo ja, dan moet deze er uit.
