### ISSUE TITLE
recurring error in archiefbeheercomponent

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefbeheercomponent#320]
i keep getting the error below. I can't put my finger on the cause, but when working (in my case configuring) in the ABC every 10 minutes i get this. Only after throwing away my browser cookies and logging in again, i can continue. 

![image](https://user-images.githubusercontent.com/96970/221200739-3edb02ce-6043-4913-a5bc-7eaefcea567a.png)

*edited*

**Comment by JurjenBert** [comment]
Thanks @joeribekker for the edit / and for conveniently adding this to the ticket system 🙂 next time ill do it myself.

**Comment by JurjenBert** [comment]
resolved

**Comment by joeribekker** [comment]
I'm curious how :)
