### ISSUE TITLE
Als recordmanager wil ik kunnen filteren en sorteren op beschikbare kolommen bij opstellen van een vernietigingslijst

### ISSUE THREAD

**Issue by svenvandescheur** [maykinmedia/archiefbeheercomponent#331]
Beschrijving
Als recordmanager
Wil ik per opgestelde lijst kunnen filteren en sorteren op de beschikbare kolommen
Zodat makkelijker door de lijst kan navigeren
Acceptatie criteria:
Filters/selecties toepassen op beschikbare kolommen (zie ook bijlage) :
Geadresseerde(n)van de lijst met informatieobjecten die V zijn
Resultaat
Startdatum
Einddatum
Naam/titel/inhoud/omschrijving
Toelichting/beschrijving/reden start
Behandelend afdeling
behandelend team/groep
Selectielijst
Waardering
Bewaartermijn
Startarchieftermijn
Kunnen sorteren in de lijst op alle beschikbare kolommen.
De toegepaste filtercriteria moeten zichtbaar zijn.
Meerdere filters of sorteringen kunnen tegelijkertijd actief zijn.
Prioriteit
Verwijder wat niet van toepassing is:
Must haves

**Comment by KarinMasselink** [comment]
https://dimpact.atlassian.net/browse/PZ-1754

**Comment by svenvandescheur** [comment]
TODO: sorteren
