### ISSUE TITLE
Create destruction list page (Record manager) [backend]

### ISSUE THREAD

**Issue by SilviaAmAm** [maykinmedia/archiefbeheercomponent#340]
- [x] **GET /zaken:** https://github.com/maykinmedia/open-archiefbeheer/pull/2

  Only logged in users can access. Should it be limited to a specific role?

  Paginated response.

  It should be possible to filter on all the fields of the zaak. However, OZ only supports limited filters (See OZ: /zaken/api/v1/schema/#tag/zaken/operation/zaak_list). Other filters should be taken care of by the frontend?

  Should zaken already included in a destruction list be filtered out? Do we want them displayed but disabled?

- [x] **Auth endpoint:** https://github.com/maykinmedia/open-archiefbeheer/pull/1

  For the users to log in.

- [x] **GET /reviewers** https://github.com/maykinmedia/open-archiefbeheer/pull/4

  Get all the possible users that are available to review a list. In the previous version, by default all lists had 2 reviewers and it was not possible to change the number of reviewers. 
  However, a feature was later added that if a list contained zaken with a single zaaktype and this zaaktype was on a (configured) list of zaaktypen with 'speedy review process', then the destruction list would require only one reviewer. 
  There were later requests for making the number of reviewers configurable. 
  How do we want to approach this here?

- [x] **POST /destruction-list** https://github.com/maykinmedia/open-archiefbeheer/pull/5

  Create the destruction list, with associated zaken and reviewers. Should validate that the zaken are not included in other destruction lists.

  Question: in the designs, the modal contains a 'periode' field. What is this?

  This kicks off the review process. The first reviewer receives a review-request per email.

**Comment by svenvandescheur** [comment]
> It should be possible to filter on all the fields of the zaak. However, OZ only supports limited filters (See OZ: /zaken/api/v1/schema/#tag/zaken/operation/zaak_list). Other filters should be taken care of by the frontend?

Discussed with @joeribekker , we have green light to introduce experimental features to OZ within limits. An additional query param filter should be doable if we adhere to the correct developer flow. Please discuss with @joeribekker (how to introduce) the changes required.

 > Should zaken already included in a destruction list be filtered out? Do we want them displayed but disabled?

Thats a good question, if in doubt: model the current behavior which IIRC excludes items once they are added to a list.

**Comment by svenvandescheur** [comment]
Related:  https://dimpact.atlassian.net/browse/PZ-1754
